# Generated by Django 5.2 on 2025-05-03 20:23

from django.db import migrations, models

import railway_station.models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='image',
            field=models.ImageField(null=True, upload_to=railway_station.models.train_image_path),
        ),
    ]
