# Generated by Django 5.2 on 2025-05-06 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_station', '0003_station_alter_train_cargo_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='railway_station.route')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='railway_station.train')),
            ],
            options={
                'ordering': ['-departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('journey', models.ManyToManyField(related_name='crew', to='railway_station.journey')),
            ],
            options={
                'verbose_name_plural': 'crews',
            },
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['route', 'train'], name='railway_sta_route_i_5d0947_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['departure_time', 'arrival_time'], name='railway_sta_departu_54535f_idx'),
        ),
    ]
