# Generated by Django 5.2 on 2025-05-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway_station', '0004_journey_crew_journey_railway_sta_route_i_5d0947_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
